config/routes.rb
Cms::Application.routes.draw do
  root :to => 'projects#index'
  resources :projects do
    resources :pages
  end

  devise_for :admins

  devise_for :users

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible:content, :name, :status, :project_id
  validates :name, :content, :presence => true
  validates :name, :uniqueness => true

  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name, :user_id
  validates :name, :description, :presence => true
  validates :name, :uniqueness => true

  has_many :pages
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :projects
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :find_project
  def index
    @pages = @project.pages.paginate(:page => params[:page]).per_page(5)
    #@pages = @project.pages
    respond_with(@project, @pages)
  end

  def show
    @page = Page.find(params[:id])
    respond_with(@project, @page)
  end

  def new
    @page = Page.new
    respond_with(@project, @page)
  end

  def edit
    @page = @project.pages.find(params[:id])
    respond_with(@project, @page)
  end

  def create
    @page = Page.new(params[:page])
    @page.project_id = @project.id
    @page.save
    respond_with(@project, @page)
  end

  def update
    @page = @project.pages.find(params[:id])
    @page.update_attributes(params[:page])
    respond_with(@project, @page)
  end

  def destroy
    @page = @project.pages.find(params[:id])
    @page.destroy
    respond_with(@project, @page)
  end
  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    @project = Project.find(params[:id])
    respond_with(@projects)
  end

  def new
    @project = Project.new
    respond_with(@projects)
  end

  def edit
    @project = Project.find(params[:id])
    respond_with(@projects)
  end

  def create
    @project = Project.new(params[:project])
    #@project.user_id = current_user.id
    @project.save
    respond_with(@projects)
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(params[:project])
    respond_with(@projects)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_with(@projects)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Cms
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/pages/_form.html.haml
= simple_form_for [@project, @page] do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :content

  .form-actions
    = f.button :submit

app/views/pages/edit.html.haml
= link_to(edit_project_pages_path(@project, @page) , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
  %i.icon-arrow-left
= render 'form'

app/views/pages/index.html.haml
# encoding: utf-8
= link_to( new_project_pages_path(@project, @page), class: 'btn', rel: 'tooltip', title: t('tooltips.new')) do
  %i.icon-plus
-# will_paginate @pages, previous_label: h("<"), next_label: h(">")
- if @pages.previous_page
  = link_to "< Önceki", params.merge(:page => @pages.previous_page)
Sayfa #{@pages.current_page} - #{@pages.total_pages}
- if @pages.next_page
  = link_to "Sonraki >", params.merge(:page => @pages.next_page)

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th Name
    %th Content
  - @project.pages.each do |page|
    %tr
      %td= page.name
      %td= page.content
      %td= link_to 'Göster', project_page_path(@project, page), :class => 'btn btn-primary'
      %td= link_to 'Düzenle', edit_project_pages_path(@project, page), :class => 'btn btn-info'
      %td= link_to 'Sil', [@project, page], :class => 'btn btn-danger', method: :delete, data: { confirm: 'Silmek istiyor musun?' }

app/views/pages/new.html.haml
= link_to(new_project_pages_path(@project), class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/pages/show.html.haml
= link_to(project_pages_path(@project) , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
  %i.icon-arrow-left

= link_to(edit_project_pages_path(@project, @page), class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
  %i.icon-pencil
%p
  %b Name:
  = @page.name
%p
  %b Content:
  = @page.content

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/projects/edit.html.haml
= link_to(projects_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
  %i.icon-arrow-left
= render 'form'

app/views/projects/index.html.haml
= link_to(new_project_path, class: 'btn', rel: 'tooltip', title: t('tooltips.new')) do
  %i.icon-plus


%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th Name
    %th Description
  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.description
      %td= link_to 'Göster', project_path(project), :class => 'btn btn-primary'
      %td= link_to 'Düzenle', edit_project_path(project), :class => 'btn btn-info'
      %td= link_to 'Sil', project_path(project), :class => 'btn btn-danger', method: :delete, data: { confirm: 'Silmek istiyor musun?' }

app/views/projects/new.html.haml
= link_to(projects_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/projects/show.html.haml
= link_to(projects_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
  %i.icon-arrow-left

= link_to(edit_project_path(@project), class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
  %i.icon-pencil
%p
  %b Name:
  = @project.name
%p
  %b Description:
  = @project.description

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>